name: Check Model Artifacts for Hosting In DataRobot
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: pip install -r ./model/requirements.txt -q
      - run: pip install datarobot-drum==1.10.21
      - run: echo "running datarobot drum validation"
      - run: drum --code-dir ./model --input test_data.csv
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Checking compatibility with DataRobot Custom Inference 
        run: python custom_inference_test.py
        env: 
          DATAROBOT_API_TOKEN: ${{ secrets.DATAROBOT_API_TOKEN }}
          DATAROBOT_ENDPOINT: https://app.datarobot.com/api/v2
